### ISSUE TITLE
sayid-buf-replay-with-inner-trace not found

### ISSUE THREAD

**Issue by DonyorM** [bpiel/sayid#15]
I'm not finding the `sayid-buf-replay-with-inner-trace` function in my M-x listing in emacs. I'm trying to create new bindings for sayid in Emacs, but it seems that function doesn't exist.

I am running the develop branch of Spacemacs in emacs 24.
I added sayid with the following package code:
```
(sayid :location (recipe :fetcher github
                             :repo bpiel/sayid
                             :files ("src/el/*.el")))
```

**Comment by bpiel** [comment]
I removed that function (and some others) in the last release, because they no longer worked. I must've forgot to remove the bindings. You can safely skip that one.

**Comment by DonyorM** [comment]
Great, I needed the letter for something else anyway. :)
