### ISSUE TITLE
Rerunning same function multiple times

### ISSUE THREAD

**Issue by DonyorM** [bpiel/sayid#16]
So I'm trying to get sayid to run trace a function multiple times. I trace the function and then run it with `cider-load-buffer`. The first time I do this, it works great, I can open the workspace and view all of my returns. However, once I try to run it again, nothing happens. Pressing `C` in the sayid buffer does not seem to affect anything.

Is this a bug? Or am I doing something wrong?

**Comment by bpiel** [comment]
Does the buffer contain the `defn`s for the functions that you've traced? If so, when you load the buffer, you're redefing the vars and removing the trace instrumentation.

**Comment by DonyorM** [comment]
No the buffer does not, I used a different buffer to do this, but I think I was reloading cider, which may have been the issue.

**Comment by bpiel** [comment]
I'm assuming the issue is resolved. Please reopen, if not.
