### ISSUE TITLE
Submit package to MELPA

### ISSUE THREAD

**Issue by abcdw** [bpiel/sayid#19]
Plz place package to MELPA repo.

I work on layer for spacemacs and it a little bit hacky to use packages from non-melpa and non-gnu repos.

**Comment by bpiel** [comment]
I started on this a bit ago, but turned out that my elisp wasn't in compliance and I lost my motivation. 

But, now that I know someone else cares, I'll get it done. thanks

**Comment by bpiel** [comment]
Yeah, for example, flycheck wants me to docstring every function. I have a lot of functions. This will take some time.

**Comment by abcdw** [comment]
It's not a problem. I will use a hacky way to get you package until you finish. Thanks a lot.

**Comment by abcdw** [comment]
Any updates? Maybe u need some help?

**Comment by bpiel** [comment]
@abcdw Thanks for the offer, but I've actually done most of the work I think. I've been out of town, but will get back to this when I'm back Tuesday evening.

**Comment by abcdw** [comment]
Great news, thanks a lot for you work!

**Comment by bpiel** [comment]
@abcdw PR to MELPA is out. We'll see what happens.

https://github.com/melpa/melpa/pull/4578

**Comment by abcdw** [comment]
See some comments from melpa devs. Subscribed for an issue, hope it will be ready soon. Thank you =)

**Comment by abcdw** [comment]
Good job, nice to see you PR merged in melpa =) Think that the package will be available in few hours.

**Comment by bpiel** [comment]
@abcdw I'll put out a stable version (which will include the improvements required to get accepted to melpa) soon -- probably this weekend.

**Comment by bpiel** [comment]
@abcdw just pushed v0.0.14 to github, so I expect it to be on melpa soon. New version is up on clojars as well, and they are both incompatible with <v0.0.13.

Also, note new installation for emacs:
https://github.com/bpiel/sayid/blob/3e5456cade044f01eb0753aabc9e50868000bd14/src/el/sayid.el#L29

I'll close this out now. Thanks for the encouragement.

**Comment by abcdw** [comment]
http://bpiel.github.io/sayid/

`C-c s` is undefined now.

**Comment by abcdw** [comment]
It works great! Thank a lot.
