### ISSUE TITLE
Sayid Spacemacs Layer

### ISSUE THREAD

**Issue by DonyorM** [bpiel/sayid#28]
Just letting you know that I submitted a pull request for adding sayid to the spacemacs clojure layer. No response yet, but progress has been made.

https://github.com/syl20bnr/spacemacs/pull/8536

**Comment by bpiel** [comment]
@DonyorM Thanks!

**Comment by DonyorM** [comment]
@bpiel Sayid has been added to the develop branch!

https://github.com/syl20bnr/spacemacs/commit/cfe0295875e78c7a29df48b1e07e06650c5c3988

**Comment by bpiel** [comment]
@DonyorM whoa, thanks!
