### ISSUE TITLE
support *.cljc files

### ISSUE THREAD

**Issue by ftravers** [bpiel/sayid#4]
Did the `C-c s t p`.  Instrumented my code, which is just one `*.cljc` file.  Ran it and then did the `C-c s w` bit and it showed the trace report.  Went into the report and hit enter on first line/column, the `v`.  Got error: `"File not found: omn1/core2.cljc"`.

My source tree looks like:

     src
     |-- clj
     `-- cljc
         `-- omn1
             `-- core2.cljc

My guess is you dont look in `src/cljc` dir for files?

**Comment by bpiel** [comment]
@ftravers My guess is that you're running into an unfortunate and undocumented gotcha. In order for sayid to find files, it needs to have certain meta data with the absolute path to *any* file (although you only have one in this case) in that `source-path`. This only becomes available when you eval one of those files with cider. I would love to figure out a way to get around this, of course.

So, my theory is, if you:
- clear the trace log ( `C-c s c`)
- eval that file with cider
- run your code 
- bring up the trace

, then you will be able to jump to lines in the source file as expected.

Please let me know if this doesn't work. I've never used *.cljc files, so I'm not ruling that out as a possible problem.

Thanks for filing an issue.

**Comment by ftravers** [comment]
This works.  Seems `*.cljc` files are fine.
